name: CI
on:
  push:
  pull_request:
    branches: [ master ]
  
jobs:
  test:
    name: pseudoBioMedIT
    runs-on: ubuntu-latest
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
  run-wf:
    name: pseudo-wf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nf-core/setup-nextflow@v1.2.0
      - run: nextflow run ${GITHUB_WORKSPACE}