name: CI
on:
  push:
  pull_request:
    branches: [ master ]
  
jobs:
  podman:
    name: pseudoBioMedIT
    runs-on: ubuntu-latest
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          touch /etc/systemd/system/user@.service.d/delegate.conf
          echo '[Service]/nDelegate=memory pids cpu cpuset' > /etc/systemd/system/user@.service.d/delegate.conf
  nextflow-devrun:
    name: run-wf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nf-core/setup-nextflow@v1.2.0
      - run: nextflow run -profile dev ${GITHUB_WORKSPACE}