name: CI
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  test:
    name: pseudoBioMedIT
    runs-on: ubuntu-latest
    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
      - name: Setup Nextflow and run pipeline
        - uses: actions/checkout@v3
        - uses: nf-core/setup-nextflow@v1.2.0
        - run: nextflow run ${GITHUB_WORKSPACE} -profile dev

